---
title: "BSoE & GC Internal Workshop 2025"
format: 
  html:
    page-layout: article
    include-in-header:
      text: |
        <meta name="robots" content="noindex">
---

We are happy to invite you to the Berlin School of Economics and DIW Graduate Graduate Center Internal Workshop for first-year PhD students. 

# Time and Location

The workshop will take place on **28 April 2025**, starting at **17:00**. After presentations, food and drink will be provided. It will take place at 

Elinor Ostrom Hall  
DIW Berlin  
Mohrenstrasse 58  
10117 Berlin.  


# Registration

This is a chance to present masters theses, work in progress, reasearch ideas, or topics of interest to fellow PhD students. Presentations will be around 20 minutes (including discussion).

**Please register [here](https://forms.gle/SGXcocg4MTwpkkA3A) by 20 April 2025** if you would like to attend or present.

# Program

You can download the program [here](/files/bgiw_program.pdf){target="_blank"}. Time for presentations and discussion is limited to 20 minutes. Presenters may take questions during presentations or reserve time for questions at the end at their dicretion. 

```{=html}
<iframe src="/files/bgiw_program.pdf" width="100%" height="450" frameborder="no" border="0" marginwidth="0" marginheight="0"></iframe>
```



----------

Workshop Organizers: Alexander Grawe, Maria Kagkeli, Andreea Stoica, and Fan Yin

In case of questions, feel free to reach out to the organizers or Email [agrawe@diw.de](mailto:agrawe@diw.de)