---
title: "Research"
format: 
  html:
    respect-user-color-scheme: true
    include-in-header:
      text: |
        <meta name="robots" content="noindex">
---

::: {.minimal}

## Work in Progress

::: {.paper}
[Sibling Spillovers in Education]{.paper-title} [Draft coming soon]{.paper-status}

[with Maximilian Bach & [Jan Marcus](https://sites.google.com/site/researchjmarcus)]{.paper-authors}

<details>
<summary>Abstract</summary>
<p>
School starting age regulations are a globally applied policy measure. However, the literature on this policy measure focuses almost exclusively on the directly affected children and neglects potential spillover effects on siblings. This study examines whether a child's school starting age also affects the educational outcomes of the child's younger siblings.
Relying on German Census data and exploiting variation in older sibling's school-track assignment resulting from school starting age, we find that the track of the older sibling increases the younger siblings' probability to attend the same track. These effects are robust across two complementary research designs: a regression discontinuity design that focuses on children born around the cutoff date for school entry and a difference-in-differences design that exploits variation in the school entry cutoffs across and within states.
The findings show that educational policies have effects beyond those directly affected: Policies focusing on older siblings might generate substantial spillover effects for younger siblings and have the potential to reduce educational inequality.
</p>
</details>

<details>
<summary>Presentations</summary>
<p>
2025: Workshop on Empirical Microeconomics (Halle); NU:DE Workshop on Applied Microeconomics (Nuremberg)
</p>
</details>
:::

::: {.paper}
[Distant Crises, Close Consequences: The Effects of Crises Abroad]{.paper-title}

[with Dilasa Karakaya]{.paper-authors}
:::

:::
